### ISSUE TITLE
gl2ps conda package incompatible with recent zlib

### ISSUE THREAD

**Issue by vepadulano** [conda-forge/gl2ps-feedstock#10]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

In the context of updating the ROOT conda-forge feedstock at https://github.com/conda-forge/root-feedstock I am now finding this error

```
Could not solve for environment specs
The following packages are incompatible
├─ libzlib 1.3.1.* h4ab18f5_1 is installable and it requires
│  └─ zlib 1.3.1 *_1, which can be installed;
└─ root_base 6.32.0.* py310h52bfb0e_0 is not installable because it requires
   └─ gl2ps >=1.4.2,<1.4.3.0a0 , which requires
      └─ zlib >=1.2.11,<1.3.0a0 , which conflicts with any installable versions previously reported.
```

Can it be that this feedstock needs a rerender or an update to the recipe? Thanks for the help!

### Installed packages

```shell
Not using any conda environment in particular
```

### Environment info

```shell
Not using any conda environment in particular
```

**Comment by chrisburr** [comment]
Hopefully this is fixed by https://github.com/conda-forge/gl2ps-feedstock/pull/12
